#!groovy

// Generated by IBM TransformationAdvisor
// Wed Oct 03 18:21:26 UTC 2018

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}